### ISSUE TITLE
Openrpc document is not correct

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/web3_proxy#146]
Using a generator on the currently deployed openrpc doc will fail with various errors (cleaning up one error will lead to a new one etc). The linked playground, once pointed to the hosted doc, will also not work: the generated client stays as the default (or blank page after refresh), and the browser console will show errors

**Comment by timurgordon** [comment]
There are a few things going wrong:

- [ ] The sftpgo client library does not contain the attribute [openrpc: exclude] on it's client struct and client factory function, which instructs the document generator to not consider these as OpenRPC components's and methods. (Since client initialization wouldn't take place over RPC, the assumption is that the clients are already running.) 
- [ ] The necessity of the [openrpc: exclude] attribute is not mentioned clearly in lib's and project's README.
- [ ] Metrics client library RPC call is not declared in the standard other clients follow, where the client is the receiver of the function. This is presumably because methods can't be declared outside modules. Solution can be either to move metrics into explorer or ignore get_metrics_url function in openrpc document.
- [ ] The openrpc docgen is configured to parse only public structs and functions, thus causing the generated document to miss some necessary component definitions.
- [ ] OpenRPC document for 3lang is being generated as well, but is there a 3lang OpenRPC server?
- [ ] The Uint128 type imported from vlib's math.unsigned lacks a schema definition as the type isn't defined within the library. This highlights a larger issue with how external functions and structs should be defined with json schemas
