### ISSUE TITLE
embed openrpc playground in the web3_proxy

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/web3_proxy#40]
mount the openrpc app on /playground maybe?

**Comment by timurgordon** [comment]
Can we close this since [playground](https://threefoldtech.github.io/web3_proxy/playground/?schemaUrl=../openrpc/btc/openrpc.json) is embedded and works? 

While playground for some other clients doesn't work, that is not related to the embedding and serving of the playground itself but the generated faulty document which will be fixed anyway upon the closure of #146

**Comment by despiegk** [comment]
not needed moved to spiderlib
